#
# Debug level
#	0 = NONE (no debug messages)
#	1 = MAJOR (only major messages)
#	2 = MINOR (also minor messages)
#	3 = VERBOSE (all messages)
#
EithonDebugLevel: 1

#
# The time that Nausea is active from the time when the user activates the TelePad
#
NauseaTicks: 200

#
# The time that Slowness is active from the time when the user activates the TelePad
#
SlownessTicks: 0

#
# The time that Blindness is active from the time when the user activates the TelePad
#
BlindnessTicks: 0

#
# After how long time (from the activation time) should we disable all effects
#
DisableEffectsAfterTicks: 120

#
# From the time when the user activates the TelePad, how long until we actually TelePad
#
TeleportAfterTicks: 100

#
# The time to wait before we load the telepad data from file
#
SecondsBeforeLoad: 5.0

#
# Cool down period before you can jump again
#
SecondsToPauseBeforeNextTeleport: 5

messages:

  #
  # Parameters: <telepad name> (%s)
  TelePadAdded: TelePad %s has been added.

  #
  # Parameters: <telepad name> (%s)
  TelePadRemoved: TelePad %s has been removed.

  #
  # Parameters: <telepad name> (%s)
  NextStepAfterAdd: Now link this telepad with command /telepad link %s <other telepad name>.

  #
  # Parameters: <telepad name 1> (%s) <telepad name 2> (%s)
  TelePadsLinked: TelePad %s and %s has been linked.

  #
  # Parameters: <telepad name> (%s)
  GotoTelepad: You have been teleported to TelePad %s.

  #
  # Parameters: NONE
  MovedOffTelePad_0: You moved away from the telepad, cancelling teleport.

  #
  # Parameters: <telepad name> (%s)
  UnknownTelePad_1: Unknown telepad (%s).






